name: Mohamed Atia Zaky

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Before'
        run: ls
      - uses: actions/checkout@v3

      - name: 'Afterr'
        run: ls
